apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 0
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: milan118/k8s_prod:latest
        env:
        - name: MONGODB_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-pasw
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
